"use client";
import {useEffect,useState} from "react";
import { Thermometer,RefreshCw,ExternalLink,Database,FlaskConical,Check,Clock,AlertTriangle } from "lucide-react";
import {empty,replay,delta,messages,failure,type State,type Reading} from "../lib/reading";
const fixtureNames=[['normal-d1-a','D1 첫 조회'],['normal-d1-b','D1 재조회'],['normal-d2','D2 정상'],['timeout','느린 응답'],['auth-401','401 거절'],['rate-429','호출 제한'],['offline','오프라인'],['schema-break','형식 변경'],['recover-d2','다시 시도 · D2 복구']];
function time(s?:string|null){return s?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'medium',timeStyle:'medium',hour12:false}).format(new Date(s)):s===null?'출처 시각 미제공':'아직 기록 없음';}
function number(n:number){return new Intl.NumberFormat('ko-KR',{maximumFractionDigits:3}).format(n);}
export default function Page(){
 const [live,setLive]=useState<State>(empty),[synthetic,setSynthetic]=useState<State>(empty),[mode,setMode]=useState<'live'|'test'>('live'),[busy,setBusy]=useState(false),[fixtures,setFixtures]=useState<Record<string,any>>({}),[selected,setSelected]=useState(''),[checks,setChecks]=useState<any[]>([]),[hashes,setHashes]=useState<any>(null),[note,setNote]=useState('');
 useEffect(()=>{fetch('/api/reading').then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<State>;}).then(setLive).catch(()=>setLive(s=>failure(s,'storage')));Promise.all(fixtureNames.map(async([name])=>[name,await (await fetch('/t04/fixtures/'+name+'.json')).json()])).then(pairs=>setFixtures(Object.fromEntries(pairs))).catch(()=>setNote('합성 파일을 불러오지 못했어요. 페이지를 다시 열어 주세요.'));fetch('/t04/hash-verification.json').then(r=>r.json()).then(setHashes).catch(()=>{});},[]);
 async function refresh(){setBusy(true);try{const r=await fetch('/api/reading',{method:'POST'});const s:any=await r.json();if(s.rows){setLive(s);setNote(s.notice||"");}else setLive(v=>failure(v,'storage'));}catch{setLive(s=>failure(s,'offline'));}finally{setBusy(false);}}
 function play(name:string){if(!fixtures[name])return;setSynthetic(s=>replay(s,fixtures[name]));setSelected(fixtures[name].fixture_id);}
 function baseline(){let s=replay(empty,fixtures['normal-d1-a']);return replay(s,fixtures['normal-d1-b']);}
 function testFailure(name:string){if(!fixtures[name])return;setSynthetic(replay(baseline(),fixtures[name]));setSelected(fixtures[name].fixture_id);}
 function runAll(){if(Object.keys(fixtures).length!==9)return;const result:any[]=[];let s=empty;for(const name of ['normal-d1-a','normal-d1-b','normal-d1-b','normal-d2']){s=replay(s,fixtures[name]);verify(name,s,result);}for(const name of ['timeout','auth-401','rate-429','offline','schema-break']){s=replay(baseline(),fixtures[name]);verify(name,s,result);s=replay(s,fixtures['recover-d2']);verify('recover-d2',s,result);s=replay(s,fixtures['recover-d2']);verify('recover-d2',s,result);}setChecks(result);setSynthetic(s);setSelected('전체 검사 완료 · '+result.filter(r=>r.pass).length+'/'+result.length);}
 function verify(name:string,s:State,list:any[]){const e=fixtures[name].expected;const last=s.rows.at(-1);const pass=s.freshness===e.freshness&&s.error_code===e.error_code&&s.rows.length===e.row_count&&last?.normalized_value===e.stored_value&&delta(s.rows)===e.delta;list.push({name:fixtures[name].fixture_id,pass,rows:s.rows.length,value:last?.normalized_value,error:s.error_code});}
 const state=mode==='live'?live:synthetic,last=state.rows.at(-1),change=delta(state.rows),problem=messages[state.error_code],previous=state.rows.at(-2),isYesterday=previous&&last&&Math.round((Date.parse(last.record_date+'T00:00:00+09:00')-Date.parse(previous.record_date+'T00:00:00+09:00'))/86400000)===1;
 return <main>
  <header className="topbar"><a href="/" className="brand"><span className="brandmark"><Thermometer size={21}/></span>오늘의 진짜 정보판</a><span className="timezone">Asia/Seoul <b>KST · UTC+9</b></span></header>
  <div className="pageheading"><div><p className="eyebrow">DAILY SIGNAL / SEOUL</p><h1>오늘의 서울 기온</h1><p className="intro">서울 중심 좌표의 현재 시간대 기온 예측값. 공개 기상 모델 기반이며 실측값은 아닙니다.</p></div><span className="location">37.5665° N · 126.9780° E</span></div>
  <nav className="tabs" aria-label="데이터 종류"><button className={mode==='live'?'active':''} onClick={()=>setMode('live')}><Database size={17}/>실제 데이터</button><button className={mode==='test'?'active':''} onClick={()=>setMode('test')}><FlaskConical size={17}/>합성 실패 검사</button></nav>
  {mode==='test'&&<div className="testnotice"><FlaskConical size={20}/><div><strong>공식 합성 시험값만 사용해요</strong><p>단위는 pt, 날짜는 가상 D1/D2입니다. 실제 서울 기온 및 실제 이틀 기록에 합산되지 않습니다.</p></div></div>}
  <section className="overview">
   <article className="valuecard"><div className="cardtop"><span>{mode==='live'?'현재 시간대 예측 기온':'합성 지표'}</span><span className={'status '+state.freshness}>{state.freshness==='fresh'?'정상 · fresh':state.freshness==='stale'?'오래된 값 · stale':state.freshness==='error'?'조회 실패 · error':'첫 조회 대기'}</span></div><div className="temperature">{last?number(last.normalized_value):'—'}<span>{last?.unit||(mode==='live'?'°C':'pt')}</span></div><div className="comparison"><span>{isYesterday?'어제 대비':'이전 기록 대비'}</span><strong>{change===null?'기록이 2건 필요해요':`${change>0?'+':''}${number(change)} ${last?.unit}`}</strong></div>{previous&&last&&<p className="calc">{last.record_date} {last.normalized_value} − {previous.record_date} {previous.normalized_value} = {change} {last.unit}</p>}<div className="valuefoot"><Clock size={15}/>{last?'마지막 정상 조회 '+time(last.fetched_at):'실제 조회 버튼을 눌러 첫 기록을 남겨 주세요.'}</div></article>
   <article className="detailscard"><div className="cardtop"><h2>값의 맥락</h2><button className="primary" onClick={mode==='live'?refresh:()=>play('recover-d2')} disabled={busy||(mode==='test'&&!fixtures['recover-d2'])}><RefreshCw size={16} className={busy?'spin':''}/>{busy?'조회 중…':mode==='test'?'다시 시도 · D2 복구':'실제 조회 / 다시 시도'}</button></div><dl><div><dt>출처</dt><dd>{last?<a href={last.source_url} target="_blank" rel="noreferrer">{last.source_name}<ExternalLink size={13}/></a>:'MET Norway (아직 조회 전)'}</dd></div><div><dt>출처 시각</dt><dd>{time(last?.source_time)}</dd></div><div><dt>조회 시각</dt><dd>{time(last?.fetched_at)}</dd></div><div><dt>기록 기준</dt><dd>Asia/Seoul · KST (UTC+9)</dd></div><div><dt>조회 날짜 키</dt><dd>{last?.record_date||'—'}</dd></div></dl><p className="muted">출처 시각은 예측의 대상 시각, 조회 시각은 응답을 받은 서버 시각입니다. 제공처의 캐시 유효기간에는 저장값을 재사용합니다. 1시간 지난 값은 오래된 값으로 표시합니다.</p></article>
  </section>
  {mode==='live'&&note&&<p className="muted" role="status">{note}</p>}
  {problem&&<aside className="errorbox" role="alert"><AlertTriangle size={22}/><div><h3>{problem.title}</h3><p>{problem.body}</p><strong>{problem.action}</strong><p className="errorcode">상태: {state.freshness} / error_code: {state.error_code} · 시도 {time(state.attempted_at)}</p></div></aside>}
  {mode==='test'&&<section className="panel"><div className="sectionhead"><div><p className="eyebrow">REPLAY LAB</p><h2>다섯 실패와 회복</h2></div><button className="secondary" onClick={()=>{setSynthetic(empty);setSelected('reset');setChecks([]);}}>합성 상태 초기화</button></div><p>실패 버튼은 D1-A → D1-B를 먼저 재생해 정상값 105를 만든 뒤 해당 오류를 재생합니다.</p><div className="failurebuttons">{fixtureNames.slice(3,8).map(([name,label])=><button key={name} className="secondary" disabled={!fixtures[name]} onClick={()=>testFailure(name)}>{label}</button>)}</div><div className="manual"><span>개별 재생</span>{fixtureNames.filter((_,i)=>i<3||i===8).map(([name,label])=><button key={name} disabled={!fixtures[name]} onClick={()=>play(name)}>{label}</button>)}</div><div className="testsummary"><code>{selected||'아직 재생하지 않았어요'}</code><span>행 {state.rows.length}건 · {state.freshness} / {state.error_code}</span><button className="primary" disabled={Object.keys(fixtures).length!==9} onClick={runAll}>전체 자동 검사</button></div>{checks.length>0&&<div className="checks" aria-live="polite">{checks.map((r,i)=><div key={i}><span className={r.pass?'pass':'fail'}>{r.pass?'통과':'실패'}</span><code>{r.name}</code><span>{r.rows}행 · {r.value} pt · {r.error}</span></div>)}</div>}{note&&<p role="alert">{note}</p>}</section>}
  <section className="panel"><div className="sectionhead"><div><p className="eyebrow">DAILY RECORD</p><h2>{mode==='live'?'실제 일별 기록':'합성 일별 기록'}</h2></div><span className="count">{state.rows.length}건</span></div><p>{mode==='live'?'같은 KST 날짜의 성공 조회는 한 행으로 갱신합니다. 실패하면 기존 행을 보존합니다.':'가상 날짜별 저장 상태입니다. 같은 날짜의 재조회와 복구는 새 중복 행을 만들지 않습니다.'}</p><div className="tablewrap"><table><thead><tr><th>KST 조회 날짜</th><th>저장값 = 화면값</th><th>출처 시각</th><th>조회 시각</th><th>출처</th></tr></thead><tbody>{state.rows.map(r=><tr key={r.id}><td><strong>{r.record_date}</strong><small>{r.id}</small></td><td className="numeric">{number(r.normalized_value)} {r.unit}</td><td>{time(r.source_time)}</td><td>{time(r.fetched_at)}</td><td><a href={r.source_url} target="_blank" rel="noreferrer">{r.source_name}<ExternalLink size={13}/></a></td></tr>)}</tbody></table></div>{!state.rows.length&&<div className="emptystate">아직 저장된 기록이 없어요. {mode==='live'?'실제 조회를 시작하세요.':'정상 D1을 재생하거나 실패 버튼을 누르세요.'}</div>}{mode==='live'&&<div className="recordguide"><Check size={18}/><span>{live.rows.length>=2?'두 날짜의 값은 아래 원자료 대조에서 확인할 수 있어요.':'실제 이틀 확인: 첫 기록 후 다른 KST 날짜에 다시 조회하세요. 합성 D1/D2로 대체할 수 없어요.'}</span></div>}</section>
  <section className="panel evidence"><div className="sectionhead"><div><p className="eyebrow">DATA PROVENANCE</p><h2>원자료 · 저장값 · 화면값 대조</h2></div></div>{state.rows.length?state.rows.map(r=><details key={r.id}><summary>{r.record_date} · {r.normalized_value} {r.unit} · 대조 보기</summary><div className="triptych"><div><h3>원자료</h3><pre>{JSON.stringify(r.raw,null,2)}</pre></div><div><h3>정규화 저장값</h3><pre>{JSON.stringify({...r,raw:undefined},null,2)}</pre></div><div><h3>화면값</h3><p className="auditvalue">{number(r.normalized_value)} {r.unit}</p><p>출처 시각 {time(r.source_time)}</p><p>조회 시각 {time(r.fetched_at)}</p><a href={r.source_url} target="_blank" rel="noreferrer">공개 원천 URL</a></div></div></details>):<p className="muted">조회 성공 후 날짜별 원자료와 저장값이 나타납니다.</p>}</section>
  <footer><span>키 없는 공개 데이터 · 실제 기록과 합성 검사는 분리 보존</span><div><a href="/source">소스 보기</a><a href="https://www.met.no/" target="_blank" rel="noreferrer">기상 데이터: MET Norway</a><a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0 · 기온 추출/단위 정규화</a><a href="/t04/README.md" target="_blank">공식 검사 사용법</a><a href="/t04/hash-verification.json" target="_blank">SHA-256 {hashes?.all_matched?'17/17 일치':'확인 결과'}</a></div><small>{hashes?.package_id} · 실제 이틀 영수증은 ALEPH 플랫폼에서 별도로 남겨야 합니다.</small></footer>
 </main>;
}
